#!/bin/bash
cpanm --force IO::Async
cpan Module::Install
cpanm ZMQ::Constants
cpanm ZMQ::LibZMQ3
#cpanm Markdent@0.26 Markdown::Pod@0.00
#cpanm Devel::IPerl

cat /home/jovyan/.cpanm/work/**/build.log

exit 1
